### ISSUE TITLE
Add two finger scroll functionality to touchpad

### ISSUE THREAD

**Issue by Arian04** [Arian04/android-hid-client#31]

**Comment by Arian04** [comment]
I had a thought a while ago that I should document here.

Don't operating systems usually handle gestures on their own? So maybe I just need to send proper events for finger up/down and ensure that it works for multiple fingers at the same time, then the OS can figure it out? I think? If that's all true, I'll probably just make it compliant with a standard precision touchpad spec and it should just work™

**Comment by brian6932** [comment]
I believe on Windows you'd have to have a Windows Precision Driver to use the native touchpad features https://learn.microsoft.com/windows-hardware/design/component-guidelines/touchpad-implementation-guide.

**Comment by Arian04** [comment]
implemented in 66db628dadfcd1c65e3261863319fee75caa1a3e and will be available in the next release.
