### ISSUE TITLE
Send button disappears

### ISSUE THREAD

**Issue by gaussandhisgun** [Arian04/android-hid-client#40]
**Describe the bug**
The send button next to the multiline input disappears unless the field itself is two lines high or more.

**To Reproduce**
1. Open the app
2. See the issue

**Expected behavior**
The send button is there anytime I might need it.

**Screenshots**
![изображение](https://github.com/Arian04/android-hid-client/assets/63512006/93e69de9-f715-4a65-86fb-de6507a2d04c)

**Device details (please complete the following information):**
 - Device: Redmi Note 9S
 - OS: Android 14 (GhostOS)
 - Soft Keyboard: GBoard
 - Are You Rooted? Yes
 - Root Method: Magisk 

**Additional context**
`wm size`: 1080x2400
`wm density`: 378

**Comment by Arian04** [comment]
thanks so much for all the details!! I've been really busy lately but just saw how many details you included and wanted to say that I'll try to reproduce this as soon as i have more time.

**Comment by Arian04** [comment]
I was unable to reproduce this on v2.2.1, but the UI part of the app has been pretty much entirely re-written since then. Could you test the latest release (v2.3.0) and let me know if this still happens? Thanks!

**Comment by gaussandhisgun** [comment]
yeah, it seems to be perfectly fine in its current state

**Comment by Arian04** [comment]
great, thanks!
