### ISSUE TITLE
Only touchpad option

### ISSUE THREAD

**Issue by vacuumbeef** [Arian04/android-hid-client#47]
It would be really cool to have an option to have just a touchpad on the screen - you could put your phone under the keyboard, for example, and have a basically laptop experience. Right now, in horizontal position touchpad area only takes the bottom half of the screen, so it's not really usable.

<details>
  <summary>Screenshot</summary>
  
![image](https://github.com/Arian04/android-hid-client/assets/51813411/fa2e4d1f-5524-41e4-a965-054f6a5ecde8)
  
</details>

Well it's my personal immediate wish, I don't know if anyone else would find it a good idea.

**Comment by Arian04** [comment]
good idea, I was actually getting annoyed about this earlier while trying to use it horizontally. I just need to figure out the least clunky way to implement this, because I'm not sure if this should be a setting, or if it should just be simple to "expand"/hide the manual input text box + send button

**Comment by vacuumbeef** [comment]
Personally I see the expand/hide button or something as the best way

**Comment by Arian04** [comment]
Implemented in the commit linked above. I also fixed up some general spacing issues in addition to adding this feature. Here's a screenshot with this feature enabled for reference:

![Screenshot_20240812-203136_USB HID Client](https://github.com/user-attachments/assets/5c3009ce-0ba2-4bd7-a976-349b61d59f7a)

**Comment by vacuumbeef** [comment]
I'd say it's even better.
