### ISSUE TITLE
Android 10

### ISSUE THREAD

**Issue by nf592** [Arian04/android-hid-client#53]
I want to know that it cannot be run on the Android 10 system. The input will display Error: Character Device Permissions SEEM Incorrect.
![image](https://github.com/user-attachments/assets/0da9365d-b090-4e3c-9e65-58cf155f58ed)

**Comment by Arian04** [comment]
I cant figure out what the problem is if you ignored the bug report template and omitted relevant information, so start off with adding that info.

Secondly, what happens if you click the "fix" button?

**Comment by Arian04** [comment]
closing due to disregard of bug template, insufficient information, and no response
