### ISSUE TITLE
No keystrokes being transferred from Android 11 tablet to my Windows 11 PC

### ISSUE THREAD

**Issue by scargill** [Arian04/android-hid-client#57]
I have a Teclast 11" Android 11 tablet. Loaded theAPK - look great, but when connected to my PC, nothing ends up on the PC. I can hear the connected noise when I plug the USB lead into my Windows 11 Pro USB - so nothing wrong with the lead - but no key presses getting transferred to the PC. 

Android not rooted as far as I know...

Any thoughts?

**Comment by Arian04** [comment]
your device isn't rooted? it won't work then
